public class try_catch {
    public static void main(String[] args) {
        int a=1000;
        int b=0;
        try{
        int c=a/b;
        System.out.println("The result is:"+c);
        }
        catch(Exception e){
            System.out.println("We failed to divide.Reason:");
            System.out.println(e);

        }
        System.out.println("This is the end of the program....");
    }  
}
